version:            '2'
services:
  app:
    build:          &build-rails
      context:      .
      dockerfile:   Dockerfile
      args:
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    command:        bundle exec puma
    ports:
      - 3000
    depends_on:
      - database
      - queue
    env_file:
      - .env
    environment:
      RAILS_ENV:    production
      DATABASE_HOST: database
      REDIS_URL:    redis://redis:6379/0/cache
    restart:        unless-stopped
    logging:
        options:
          max-size: "10m"
          max-file: "10"
  queue:
    build:          *build-rails
    depends_on:
      - database
      - redis
    environment:
      REDIS_URL:    redis://redis:6379/0/cache
      RAILS_ENV:    production
    command:        bundle exec sidekiq -C config/sidekiq.yml
    env_file:
      - .env
    restart:        unless-stopped
    logging:
        options:
          max-size: "10m"
          max-file: "10"
  mqtt:
    build:
      context:      ./lib/dockerfiles/mqtt
      dockerfile:   Dockerfile
    ports:
      - 1883
      - 1884
      - 3033
      - 8083
    volumes:
      - ./lib/dockerfiles/mqtt/config:/mqtt/config
    restart:        unless-stopped
    logging:
        options:
          max-size: "10m"
          max-file: "10"
  nginx:
    image:          nginx:alpine
    volumes_from:
      - app
    volumes:
      - ./lib/dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - mqtt
    ports:
      - "80:80"
    restart:        unless-stopped
    logging:
        options:
          max-size: "10m"
          max-file: "10"
  redis:
    image:          redis:4-alpine
    ports:
      - 6379
    volumes:
      - ./redis:/var/lib/redis/data
    restart:        unless-stopped
    logging:
        options:
          max-size: "10m"
          max-file: "10"
  database:
    restart:         unless-stopped
    image:           postgres:9.6-alpine
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres
      HOST:              database
    env_file:        .env
    logging:
        options:
          max-size:  "10m"
          max-file:  "10"
