default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 8
  host: localhost

development:
  <<: *default
  database: synchouse

test:
  <<: *default
  database: synchouse_test

production:
  <<: *default
  database: synchouse_production
