default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: amendoim
  pool: 8
  host: localhost

development:
  <<: *default
  database: client_web

test:
  <<: *default
  database: client_web_test

production:
  <<: *default
  database: client_web_production
